# Site settings
title: RyppleX
email: hello@bogs.world
description: > # this means to ignore newlines until "baseurl:"
 Open data platform and global community dedicated to understanding and conserving bog.
 Checkout our latest work in ecological sensing, wetland mapping, and community science!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: volnyio
github_username:  volny

# Build settings
markdown: kramdown
